apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-tokens
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ACCESS_TOKEN_SECRET: {{ default (randAlphaNum 32) .Values.secrets.accessToken | b64enc | quote }}
  LOGIN_TOKEN_SECRET: {{ default (randAlphaNum 32) .Values.secrets.loginToken | b64enc | quote }}
  REFRESH_TOKEN_SECRET: {{ default (randAlphaNum 32) .Values.secrets.refreshToken | b64enc | quote }}
  FILE_TOKEN_SECRET: {{ default (randAlphaNum 32) .Values.secrets.fileToken | b64enc | quote }}

